import 'package:freezed_annotation/freezed_annotation.dart';

part 'api_failure.freezed.dart';

/// Base type for every error that can be returned by [ItunesPodcastApi].
///
/// Use pattern matching (or [when]/[map] generated by freezed) to react to a
/// specific kind of failure.
@freezed
sealed class ApiFailure with _$ApiFailure {
  const ApiFailure._();

  /// Connection could not be established or timed out.
  const factory ApiFailure.network(
    String message, {
    Object? cause,
  }) = NetworkFailure;

  /// The request was cancelled before it completed.
  const factory ApiFailure.cancelled() = CancelledFailure;

  /// The server responded with a non-success status code.
  const factory ApiFailure.http({
    required int statusCode,
    required String message,
    Object? responseBody,
  }) = HttpFailure;

  /// A response was received but its body could not be parsed.
  const factory ApiFailure.parse(
    Object message,
    StackTrace? stackTrace,
  ) = ParseFailure;

  /// Any unexpected error that does not fit the other categories.
  const factory ApiFailure.unknown(
    Object error,
    StackTrace stackTrace,
  ) = UnknownFailure;
}
